import { Moment } from 'moment';
import { Disclaimers } from 'src/app/shared/interfaces/disclaimers';
import { GeneralRemarks } from 'src/app/shared/interfaces/general-remarks';
import { InternalNotes } from 'src/app/shared/interfaces/internal-notes';
import { PolicyForm } from 'src/app/shared/interfaces/policy-form';
import { Subjectivities } from 'src/app/shared/interfaces/subjectivities';
import { Warranties } from 'src/app/shared/interfaces/warranties';
import { Submission } from '../../submission/models/submission';
import { PropertyQuote } from './property-quote';
import { QuoteLineItem } from './quote-line-item';
import { QuoteRate } from './quote-rate';

export interface Quote {
  submissionNumber: number | null;
  quoteId: number | null;
  cuspNumber: number | null;
  quoteNumber: number | null;
  sequenceNumber: number | null;
  policyEffectiveDate: Date | null;
  policyExpirationDate: Date | null;
  status: number;
  statusDescription: string;
  claimsMadeOrOccurrence: string;
  admittedStatus: string;
  policyNumber: string | number;
  coverageCode: number | null;
  carrierCode: string;
  pacCode: string;
  submission: Submission;
  quoteName: string | null;
  policySymbol: string;
  policyMod: string | null;
  formName: string;
  terrorismCoverageSelected: boolean;
  terrorismPremium: number | null;
  terrorismTemplateCode: string;
  grossPremium: number | null;
  grossLimits: number | null;
  partOf: number | null;
  attachmentPoint: number | null;
  underlyingLimits: number | null;
  commissionRate: number | null;
  ratingBasis: number | null;
  riskSelectionComments: string | null;
  approvalRequired: boolean;
  approvalStatus: string | null;
  approvalUserName: string | null;
  approvalDate: Date | Moment | null;
  comments: string | null;
  createdBy: string | null;
  createdDate: Date | Moment | null;
  modifiedUserName: string | null;
  modifiedDate: Date | Moment | null;
  groupId: number;
  programId: number;
  validated: boolean;
  ratedPremium: number | null;
  auditCode: string | null;
  umuimAccepted: boolean;
  retainedLimit: number | null;
  approvalReason: string | null;
  retroDate: Date | Moment | null;
  quoteExpirationDate: Date | Moment | null;
  projectSpecific: boolean;
  generalAggregateLimits: number | null;
  productAggregateLimits: number | null;
  persInjAdvertInjLimits: number | null;
  fireDamageLimits: number | null;
  medicalPayments: number | null;
  fullPriorActs: boolean;
  validatedRisk: string | null;
  triaFormReceived: string | null;
  annualizedPremium: number | null;
  manualApprovalRequired: string;
  submissionGroupsStatusId: number;
  modifiedUserId: number | null;
  approvalUserId: number | null;
  terrorismCoverage: string | null;
  minimumPremiumRequired: boolean | null;
  // userFacultativeReins: boolean;
  // excessOfAuto: boolean;
  // underlyingUMLimit1Mil: boolean;
  // umuimAcceptedLastYear: boolean;
  indicationPremium: number | null;
  printedAt: Date | Moment | null;
  facTreatyType: string | null;
  premiumRate: number | null;
  ownerId: number | null;
  ownerUserId: number | null;
  // flatRateIndicator: boolean;
  // sinceInception: boolean;
  formsVersion: number | null; //intVersion in PAUL
  // specPlusEndorsement: boolean;
  // proRatePremium: boolean;
  overridePremium: boolean;
  // ratingDataChanged: boolean | null;
  rated: boolean | null;
  // overrideTRIAPremium: boolean;
  coinsurancePercentage: number | null;
  productManufactureDate: Date | Moment | null;
  // discontinuedProducts: boolean | null;
  autoCalcMiscPremium: boolean;
  minimumPremium: number | null;
  advancePremium: number | null;
  earnedPremiumPct: number | null;
  // variesByLoc: boolean;
  pcfCharge: number | null;
  pcfChargeDesc: string | null;
  professionalAggregateLimits: number | null;
  professionalLiabilityLimits: number | null;
  qsPercentTotalTRIPRAPremium: number | null;
  // quotaShare: boolean;
  qsPartOfLimits: number | null;
  qsPercentTotalPremium: number | null;
  quotaSharePercent: number | null;
  maxPolicyAggregate: string | null;
  displayCommissionRate: number;
  supportedStatus: string | null;
  quoteRates: QuoteRate[];
  quoteLineItems: QuoteLineItem[];
  propertyQuote: PropertyQuote | null;
  importWarnings: string[];
  importErrors: string[];
  naicsCode: string | null;
  sicCode: string | null;
  classCode: number | null;
  riskState: string;
  quotePolicyForms: PolicyForm[];
  subjectivityData: Subjectivities[];
  warrantyData: Warranties[];
  disclaimerData: Disclaimers[];
  generalRemarksData: GeneralRemarks[];
  internalNotesData: InternalNotes[];
  totalPremium: number | null;
  formsVersionDescription: string | null;
  departmentId: number | null;
  flatPremium: number | null;
  propertyPremium: number | null;
  propertySubTotalPremium: number | null;
  overrideMinPolPrem: boolean;
}
