export const TransactionTypes = {
  AdditionalPremium: 1,
  NewBusiness: 2,
  AuditPremium: 3,
  FlatCancel: 4,
  InstallmentPremium: 6,
  RenewalBusiness: 7,
  DepositPremium: 8,
  ReturnDeposit: 9,
  Endorsement: 10,
  AdjustmentToPremiumLayers: 11,
  ReturnPremium: 12,
  NonPremiumItems: 13,
  ShortRateCancel: 14,
  ProRataCancel: 15,
  Reinstatement: 16,
  NewBusinessProgramMasterPolicy: 17,
  RenewalBusinessProgramMasterPolicy: 18,
  CancellationOfPolicyExtension: 19,
  PolicyExtensionByEndt: 20,
  CutoffTreatyReturnPremium: 21,
  CutoffTreatyAdditionalPremium: 22,
  ERPPremium: 23,
  NonRenewal: 24,
  ReversalOfNonRenewal: 30
};
