export interface Submission {
  submissionNumber: number,
  CompanyCode: number | null | undefined,
  RegionCode: number | null | undefined,
  OfficeCode: number | null | undefined,
  DepartmentCode: number | null | undefined,
  SicCode: string,
  InsuredCode: number | null | undefined,
  ProducerCode: number | null | undefined,
  BrokerId: number | null | undefined,
  RetailProducerCode: number | null | undefined,
  PolEffDate: Date | null | undefined,
  PolExpDate: Date | null | undefined,
  QuoteDueDate: Date | null | undefined,
  ExpiringPolicyId: number | null | undefined,
  NewRenewalFlag: number | null | undefined,
  StatusCode: number | null | undefined,
  ReasonCode: number | null | undefined,
  Comments: string,
  Underwriter: number | null | undefined,
  ApplyToDate: Date | null | undefined,
  CreatedBy: number | null | undefined,
  CreatedDate: Date | null | undefined,
  ModifiedBy: number | null | undefined,
  ModifiedDate: Date | null | undefined,
  GroupId: number | null | undefined,
  EventCode: number | null | undefined,
  EventDate: Date | null | undefined,
  ProgramId: number | null | undefined,
  ContractorCode: number | null | undefined,
  RenewablePolicy: number | null | undefined,
  XrefSubNum: number | null | undefined,
  CancelDate: Date | null | undefined,
  AssistantBroker: number | null | undefined,
  ProducerContact: string,
  ProducerContactEmail: string,
  TeamId: number | null | undefined,
  UwBranchCode: string,
  businessUnit: string,
  submissionGroupId: number | null | undefined,
  businessType: string,
  producerContactId: number | null | undefined,
  naicscode: string,
  lobCode: string,
  constructionWrapup: number | null | undefined,
  processor: number | null | undefined,
  submissionEventCode: string,
  extExpiringPolicyNo: string

}
