import { Insured } from '../../insured/models/insured';
import { Producer } from './producer';
import { ProducerContact } from './producer-contact';
import { SubmissionEvent } from './submission-event';

export interface Submission {
  submissionNumber: number,
  companyCode: number | null | undefined,
  regionCode: number | null | undefined,
  officeCode: number | null | undefined,
  departmentCode: number | null | undefined,
  sicCode: string | null,
  insuredCode: number | null,
  producerCode: number | null | undefined,
  brokerId: number | null | undefined,
  retailProducerCode: number | null | undefined,
  polEffDate: Date | null | undefined,
  polExpDate: Date | null | undefined,
  quoteDueDate: Date | null | undefined,
  expiringPolicyId: number | null | undefined,
  newRenewalFlag: number | null | undefined,
  statusCode: number | null | undefined,
  reasonCode: number | null | undefined,
  comments: string | null,
  underwriter: number | null | undefined,
  applyToDate: Date | null | undefined,
  createdBy: number | null | undefined,
  createdDate: Date | null | undefined,
  modifiedBy: number | null | undefined,
  modifiedDate: Date | null | undefined,
  groupId: number | null | undefined,
  eventCode: number | null | undefined,
  eventDate: Date | null | undefined,
  programId: number | null | undefined,
  contractorCode: number | null | undefined,
  renewablePolicy: number | boolean | undefined,
  xrefSubNum: number | null | undefined,
  cancelDate: Date | null | undefined,
  assistantBroker: number | null | undefined,
  producerContactName: string | null,
  producerContactEmail: string | null,
  teamId: number | null | undefined,
  uwBranchCode: string,
  businessUnit: string,
  submissionGroupId: number | null | undefined,
  businessType: string,
  producerContactId: number | null | undefined,
  naicsCode: string | null,
  lobCode: string | null,
  constructionWrapup: number | null | undefined,
  processor: number | null | undefined,
  submissionEventCode: string,
  extExpiringPolicyNo: string | null,
  insured?: Insured | null,
  producer: Producer | null,
  producerContact: ProducerContact | null,
  submissionEvents: SubmissionEvent[] | null,
  underwriterName: string | null
}
