
export interface Insured {
    insuredCode: number
    name: string,
    formerName1: string,
    formerName2: string,
    sicCode: string,
    naicsCode: string,
    entityType: number,
    street1: string,
    street2: string,
    city: string,
    state: string,
    zip: string,
    county: string,
    country: string,
    contactName: string,
    phone: number | null,
    fax: number | null,
    email: string,
    website: string,
    comments: string,
    customerCode: number | null,
    addressOveridden: boolean,
    addressVerified: Date | null,
    fein: string,
    createdBy: string,
    createdDate: Date | null,
    modifiedBy: string,
    modifiedDate: Date  | null,
    isNew: boolean
}

export const newInsured = (): Insured => {
    return {
        insuredCode: 0,
        name: "",
        formerName1: "",
        formerName2: "",
        sicCode: "",
        naicsCode: "",
        entityType: 0,
        street1: "",
        street2: "",
        city: "",
        state: "",
        zip: "",
        county: "",
        country: "",
        contactName: "",
        phone: null,
        fax: null,
        email: "",
        website: "",
        comments: "",
        customerCode: null,
        addressOveridden: false,
        addressVerified: null,
        fein: "",
        createdBy: "",
        createdDate: null,
        modifiedBy: "",
        modifiedDate: null,
        isNew: true
    }
}